version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_prod
      - DJANGO_SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DB_NAME
      - DJANGO_DB_USER
      - DJANGO_DB_PASSWORD
      - DJANGO_DB_HOST
      - DJANGO_DB_PORT
      - DJANGO_EMAIL_HOST
      - DJANGO_EMAIL_HOST_USER
      - DJANGO_EMAIL_HOST_PASSWORD
      - DJANGO_EMAIL_PORT
      - DJANGO_EMAIL_FROM
      - DJANGO_EMAIL_SECURITY
      - DJANGO_LOG_FILE
      - DJANGO_ADMIN_EMAIL